### ISSUE TITLE
APT Source List 

### ISSUE THREAD

**Issue by bgp9249** [hn/seagate-blackarmor-nas#1]
The source list at /etc/apt/sources.list needs to be updated to point to archive.debian.org:

deb http://archive.debian.org/debian/ lenny main contrib non-free
deb-src http://archive.debian.org/debian/ lenny main contrib non-free

deb http://archive.debian.org/debian-security lenny/updates main contrib non-free
deb-src http://archive.debian.org/debian-security lenny/updates main contrib non-free

deb http://archive.debian.org/debian-volatile lenny/volatile main contrib non-free
deb-src http://archive.debian.org/debian-volatile lenny/volatile main contrib non-free

**Comment by hn** [comment]
Yes, of course. I suggest that every user manually updates the sources.list after installation. I do not want to modify the 'prehistoric' filesystem image anymore.

Please visit [Moritz Rosenthal's web page](http://wiki.ccc-ffm.de/projekte:diverses:seagate_blackarmor_nas_220_debian) for instructions on how to update to a newer (non EOL) Debian version.
