### ISSUE TITLE
Ramdisk image is corrupt or invalid

### ISSUE THREAD

**Issue by voidzwarranty** [hn/seagate-blackarmor-nas#10]
I ran through the entire process in the readme.md twice but get an error after the final reboot. The bootloader upgrade, Debian install and post install script seem to run without error.  Any ideas?

U-Boot 2017.11 (Dec 18 2018 - 09:52:13 +0100)
NAS 220

SoC:   Kirkwood 88F6281_A1
DRAM:  128 MiB
WARNING: Caches not enabled
NAND:  32 MiB
In:    serial
Out:   serial
Err:   serial
Net:   egiga0
88E1116 Initialized on egiga0
IDE:   Bus 0: .........OK Bus 1: not available
  Device 0: Model: Hitachi HDS721075KLA330  Firm: GK8OA97A Ser#: GTF202P8H9AH2F
            Type: Hard Disk
            Supports 48-bit addressing
            Capacity: 715404.8 MB = 698.6 GB (1465149168 x 512)
Hit any key to stop autoboot:  0

NAND read: device 0 offset 0xc0000, size 0x500000
 5242880 bytes read: OK

NAND read: device 0 offset 0x5c0000, size 0x1a40000
Attempt to read outside the flash area
 0 bytes read: ERROR
## Booting kernel from Legacy Image at 00040000 ...
   Image Name:   kernel 4.19.0-6-marvell
   Created:      2020-01-08   5:19:45 UTC
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2056282 Bytes = 2 MiB
   Load Address: 00040000
   Entry Point:  00040000
   Verifying Checksum ... OK
Wrong Ramdisk Image Format
Ramdisk image is corrupt or invalid
nas220>

**Comment by hn** [comment]
That's quite strange. The second NAND read (`NAND read: device 0 offset 0x5c0000, size 0x1a40000`) shouldn't fail at all (NAND size is displayed as 32 MB = 0x2000000 and offset 0x5c0000 with read size 0x1a40000 is within this range).

Try to stop U-Boot autoboot (`Hit any key to stop autoboot`) and then issue `nand read.e 0x800000 0x5c0000 0x1a40000` manually and see if this fails. Maybe you also try smaller read sizes (0x1a3ffff or even smaller).

And try `nand info` (see https://www.denx.de/wiki/DULG/UBootCmdGroupNand)

Which NAS model do you have? My 220 has SoC Kirkwood 88F6281_A0, your NAS has SoC Kirkwood 88F6281_A1

**Comment by voidzwarranty** [comment]
Reducing the length to 0x1a3ffff did the trick!   Apparently, one byte was marked bad which pushed the total length past 32M.  I appreciate the help and your efforts on this project!

**Comment by hn** [comment]
I've pushed https://github.com/hn/seagate-blackarmor-nas/commit/f8c2dc6e9f8ce7279c6f7342025cdadca35db4c5. Please do me a favor and write the env binary to NAND (`fatload usb 0:1 0x800000 u-boot-env.bin ... nand erase ... nand write ...`) and report back if everything works smoothly.
