### ISSUE TITLE
NAS 220 Upgrade from Debian-Armel 2.6.22.18 to Debian 10 Buster

### ISSUE THREAD

**Issue by EinsteinZY** [hn/seagate-blackarmor-nas#11]
Hello Hojo  @hn 

Many thanks for your reply. I'm sorry for leaving a comment under your original code changes. I am new to Github, not familiar with those functions, sorry for that.

I have a BlackArmor NAS220 and installed the Debian-Armel 2.6.22.18 by using your previous fw manual upgrade method due to I don't have a serial cable. My issues are:
1. Is it possible to upgrade the debian-armel 2.6.22.18 to latest debian 10 buster without using a serial cable?
2. If it is possible, Could you teach me how to upgrade? 
3. The main reason I install debian in my nas220 is planing to install OpenMediaVault in my nas220, is it possible to install OMV after installed debian 10 buster? 

Many thanks for your time to answer my questions.

**Comment by hn** [comment]
Hi @EinsteinZY 

1./2. I think it might be possible to repartition and flash the NAND flash from within the 'old' Debian-Armel 2.6.22.18, but I think it's not worth the effort and/or risk. An 3.3v USB serial cable costs somewhat like 5 $/€ and with the cable you have full control during flash, install and boot phase.

3. I don't know OMV in detail. All Debian 10 ARM packages should work in theory. But the NAS has limited CPU/RAM resources, that might be a showstopper.
