### ISSUE TITLE
Building this kernel

### ISSUE THREAD

**Issue by gaborszita** [hn/seagate-blackarmor-nas#14]
Greetings there!

I'm also trying to install a custom debian on my NAS. It has the same chip as yours, the 88F6-LG02. However, when I boot your image on the NAS it fails to boot, because it hits a kernel exception. So can you please provide me how you built your kernel, step-by-step?

Thank You

**Comment by gaborszita** [comment]
What I did:
I followed the steps here: https://wiki.debian.org/DebianInstaller/Arm/OtherPlatforms
However, it fails with bad checksum CRC. Your image boots, but during the boot the kernel hits an exception. I need your build instructions, because that way I can figure out what you did, since when I booted your image I didn't get bad checksum CRC.

**Comment by hn** [comment]
Having a kernel is not sufficient for (nearly all) embedded systems. You'll need a [DTS/DTB file](https://elinux.org/Device_Tree_Reference) exactly matching your hardware.

My script does not build a kernel. It uses the stock Debian kernel which is combined with a (stock Debian) [DTB file for the NAS 220](http://ftp.debian.org/debian/dists/stable/main/installer-armel/current/images/kirkwood/device-tree/kirkwood-blackarmor-nas220.dtb).

**Comment by gaborszita** [comment]
Closing
