### ISSUE TITLE
Nas 220 Debian 10 install

### ISSUE THREAD

**Issue by gigirock** [hn/seagate-blackarmor-nas#16]
Hi all, I have a nas 220 and i want to install debian 10 , i used successfully the rs232 interface and i can complete the installation ( more or less 1 hour :( ).
when i reboot the unit i have this message on monitor : 
......
**Wrong Ramdisk Image Format
Ramdisk image is corrupt or invalid** 

So I googled some, and someone said: 

_**You need to enable CONFIG_LEGACY_IMAGE_FORMAT in U-Boot:
Go to the u-boot source directory.
Type: $ make menuconfig
In Boot images -> Enable support for the legacy image format
Exit and save, then build U-Boot again
Now it will be able to load your uRamdisk :-)**_

where I can rebuild uboot ? 
Can i Do it by myself ? 

Many thanks in advance 

gigirock

**Comment by hn** [comment]
Are you really sure that flashing U-Boot worked successfully? When starting the device, it shoud show something like `U-Boot 2017.11` at the very beginning.
