### ISSUE TITLE
NAS 400 != 440 ?

### ISSUE THREAD

**Issue by karlkashofer** [hn/seagate-blackarmor-nas#17]
Hi !

Is the NAS 400 the same as NAS 440 ? i.e. does the "Warning: Support for the NAS 440 is currently alpha quality! Things are incomplete, buggy and unstable" also apply to NAS 400 ?

Thanks,
KK

**Comment by hn** [comment]
Yes, all the NAS 4XX series products have the same motherboard and 4-bay enclosure.

Check back in a few months, I think support for 4XX might stabilize over the year (I'm working on it very sporadically, it should remain a fun project).

**Comment by karlkashofer** [comment]
Thats great, i hope you can manage to get the two additional bays working !

Maybe it would be prudent to change the wording on the frontpage ?

Here "Warning: Support for the NAS 440 is currently alpha quality! " and 
here "NAS 440 patch details" to NAS 4XX ?

Thanks for your efforts,
cheers,
KK
