### ISSUE TITLE
Post install, booting can't mount anything under /root

### ISSUE THREAD

**Issue by JHarding86** [hn/seagate-blackarmor-nas#21]
I have a BlackArmor 440 so I know things aren't exactly stable. I am here to help try and get this thing going nicely for everyone.

Installation seemed to go over without a hitch. Post install as the NAS is booting failures occur attempting to mount anything under the /root directory.

```
Warning: fsck not present, so skipping root file system
[   22.435780] BTRFS info (device md1): flagging fs with big metadata feature
[   22.442743] BTRFS info (device md1): disk space caching is enabled
[   22.448974] BTRFS info (device md1): has skinny extents
done.
Begin: Running /scripts/local-bottom ... done.
Begin: Running /scripts/init-bottom ... mount: mounting /dev on /root/dev failed: No such file or directory
mount: mounting /dev on /root/dev failed: No such file or directory
done.
mount: mounting /run on /root/run failed: No such file or directory
run-init: can't execute '/sbin/init': No such file or directory
Target filesystem doesn't have requested /sbin/init.
run-init: can't execute '/sbin/init': No such file or directory
run-init: can't execute '/etc/init': No such file or directory
run-init: can't execute '/bin/init': No such file or directory
run-init: can't execute '/bin/sh': No such file or directory
run-init: can't execute '': No such file or directory
chvt: can't open console
No init found. Try passing init= bootarg.


BusyBox v1.30.1 (Debian 1:1.30.1-6+b3) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) ls
bin      dev      init     proc     run      scripts  tmp      var
conf     etc      lib      root     sbin     sys      usr
(initramfs) 
```

If I navigate into /root there is folder "@rootfs" which contains everything I would imagine should be there including the missing fsck binary.

Any idea why the root file system isn't being mounted properly?

**Comment by JHarding86** [comment]
I just reran the installation and installed on a USB stick and debian booted right up. I was trying to install to a RAID0 array, that obviously doesn't work here. Thanks for turning my useless BlackArmor into a brand new functional NAS! I'd really love to get the extra 2 bays functional.

Interesting note, the debian installer recognized a disk that I had installed in bay 2. Upon having a successful installation and booting into it, the drive did not show in /dev :(

**Comment by hn** [comment]
It is possible to install and boot Debian on a RAID0 but from your logs I can not conclude whats going wrong.

Anyway, enjoy using the NAS :)
