### ISSUE TITLE
Does BA support drives larger than 3TB?

### ISSUE THREAD

**Issue by serpro69** [hn/seagate-blackarmor-nas#23]
Hi,
Thanks a lot for your guide, it made me want to get my hands on a BA 220 to play around with. My concern is, would the BA support drives > 3TB . Do you have any info on this or tried it yourself?
Seagate explicitly mentions 3TB max capacity per drive, which may have been OK back when this NAS was released, but isn't even close to enough these days. So before I buy this NAS, I'm wondering if it would be usable for me since I'd like to put at least 6-8TB drives inside it. Preferably I'd like to put 2x18TB seagate exos drives, which would make the whole experiment worthwhile since that would give me enough storage for an external cold backup of my main NAS. I can't find any info on this online, so hopefully someone here tried this and could give me some tips on whether this would work (or not work)

**Comment by hn** [comment]
Hm, I'm pretty sure that I've tested a 2 TB drive some time ago and it worked. Don't know anything about bigger drives. The BA NAS is 15 years (!) old and I think the hardware designers did not even dream about 18 TB drives at that time :) Might work, might not, sorry I don't know.

**Comment by serpro69** [comment]
Yeah, I figured as much. Not sure if it's worth it in that case, even if I can get it very cheap and in new condition.
All I needed was a cheap two-bay NAS and then I found a new BA for 30ish USD. I knew it sounded too good to be true :D 
Thanks a lot for your answer :)
