### ISSUE TITLE
Architecture not found

### ISSUE THREAD

**Issue by jrmagots** [hn/seagate-blackarmor-nas#25]
Hi.
I found an old Blackarmor 220, and I'm trying to install Debian 10 following the instructions here.
I'm stucked in the "Choose a mirror of debian archive" during the debian 10 instalation
I found that the Debian 10 packages was migrated to archive, but I don't know how to point the instalation to the new source.

Could someone help me?

Ps: I know the debian 10 isin't supported and all the security problems with it. But for this hardware it is still the better solution to keep using this hardware. I will use it just to store some DLNA music and videos.

**Comment by hn** [comment]
IIRC there is an option 'enter information manually' within the 'choose mirror' dialogue. Likely you have to enter 'archive.debian.org' there. Try searching the web on how to install old versions of Debian, e.g. [here](https://forums.debian.net/viewtopic.php?t=81451)

**Comment by jrmagots** [comment]
Hi Hn \o/
It worked, thank you! I successfully installed the debian 10.

But I'm not able to install the Uboot on flash, I do all the commands but it freezes when I send the reboot command, and then I need to start again.


```
nas220> usb start
starting USB...
Bus ehci@50000: USB EHCI 1.00
scanning bus ehci@50000 for devices... 3 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
nas220> fatload usb 0:1 0x800000 u-boot-nas220.kwb
591616 bytes read in 24 ms (23.5 MiB/s)
nas220> nand erase 0x0 0x87200

NAND erase: device 0 offset 0x0, size 0x87200
Erasing at 0x84000 -- 100% complete.
OK
nas220> nand write 0x800000 0x0 0x87200

NAND write: device 0 offset 0x0, size 0x87200
 553472 bytes written: OK
nas220> fatload usb 0:1 0x800000 u-boot-env.bin
65536 bytes read in 11 ms (5.7 MiB/s)
nas220> nand erase 0xA0000 0x10000

NAND erase: device 0 offset 0xa0000, size 0x10000
Erasing at 0xac000 -- 100% complete.
OK
nas220> nand write 0x800000 0xA0000 0x10000

NAND write: device 0 offset 0xa0000, size 0x10000
 65536 bytes written: OK
nas220> reset
resetting ...
```

**Comment by hn** [comment]
I do not understand your problem. Flashing seems to be successful. If you restart the system and U-Boot displays version 2022.04, everything is fine.

**Comment by jrmagots** [comment]
After de reset command, I remove the USB Stick, and unplug and plug the power cord. But debian doesn't boot.
No sign on the serial terminal ttyUSB0.

Then, I need to use the unbrick command bellow to get to serial terminal again
kwboot -b u-boot-nas220.kwb -p -t /dev/ttyUSB0

On terminal using the unbrik command, I followed the flash bootloader steps again but no result, still no boot

**Comment by hn** [comment]
You copy-pasted `0x87200` as the size parameter for flashing from the project page (which only is an example). You need to use the size parameter from the output from the prep-script. You only flashed a fraction of the U-Boot loader.

**Comment by jrmagots** [comment]
My mistake Hn, sorry
I re run the prep-script follow the commands and it worked \o/
Thank you again, My NAS220 got a new life with debian!  I will use it with samba and minidnla to store and stream dlna videos to my TV.

**Comment by hn** [comment]
Please star this repo if you like it.
