### ISSUE TITLE
Read/Write speeds

### ISSUE THREAD

**Issue by jrmagots** [hn/seagate-blackarmor-nas#26]
I'm sucssefully runing debian 10 on NAS220

I thought with debian I'll get better read/write speeds than the official firmware. 
With official firmware and with debian 10 I got 18 MiB B/s on read and 12 MiB B/s on write. Even with an Sata SSD Drive =/ and Gigabit network. I'll test, but I guess it will not be enough to share 4k videos to my SmartTV.

Just to know. Did you get better speeds? Any hint? \o/

Thank you again

**Comment by hn** [comment]
The BA NAS was built about 15 years ago. I don't think there was 4k video at that time :)
