### ISSUE TITLE
SP99 is not making any changes in the system, debian is not booting. 

### ISSUE THREAD

**Issue by rkozka** [hn/seagate-blackarmor-nas#3]
Hi, after updating device with custom-sg2000-2000.1337.sp99.img the password for root@<NAS IP> is not 'root' like you said, i get incorrect password error.  Now i cant connect to my device :(

**Comment by mjseeley** [comment]
try toor or shasta. I had that issue ages ago too.

**Comment by rkozka** [comment]
No luck for me... i wiped hdd and started from beginning, first i applied SP42 patch and it works, i can access ssh with root and atsahs password. Then i patched firmware SP99 for debian install and it wont do anything, i still can log with ssh on root and atsahs password so it seems like nothing is changed after patching with SP99.  Of course debian image is sitting in Public folder. It is blackarmor 110, is it possible that this project is not compatible with bs110 version? 
![capture](https://cloud.githubusercontent.com/assets/9077931/17214378/ed63b3c2-54d8-11e6-836b-b0472a12989d.PNG)

**Comment by hn** [comment]
SP42 sets the root pw to `atsahs`.

It seems that SP99 isn't applied at all at your setup. Try to check if the md5sum is correct. The SP99 `post_setup.sh` works like this:

```
if [ ! -d /DataVolume/Public ]; then
        exit 0
fi

cd /DataVolume/Public

if [ -f custom-rootfs_full.tar.gz -a -f custom-rootfs_full.tar.gz.md5 ]; then

        md5sum -c custom-rootfs_full.tar.gz.md5
        if [ "$?" -ne "0" ]; then
                exit
        fi
```

**Comment by rkozka** [comment]
Hi, thanks for reply. I've checked md5 sum, its correct. Can you tell me more about SP99 patch, how it work? How can i verify or check if patching SP99 has made any changes in BA's system? Is there a way i can somehow manually kickstart booting of your debian image laying in /DataVolume/Public?

**Comment by hn** [comment]
Deobfuscate the firmware image (see _5. Deobfuscate Seagate firmware image (.img -> .tgz)_ in `seagate-blackarmor-nas.txt`) and unpack the resulting file (`tar xvzf ...`). Then you'll see the files

```
pre_setup.sh
post_setup.sh
sp
sp.tgz
sp.tgz.md5
forallver
```

The `*.sh`-files contain the logic for the installation. You can even add some debug code an re-pack/obfuscate the firmware file.

**Comment by rkozka** [comment]
this is output of manually running post_setup.sh script on my rooted BS, looks like md5sum command is not working well on this device, can i skip md5sum check in script?

http://pastebin.com/iJTsvJNu

**Comment by hn** [comment]
The pastebin thing looks like garbage ...

I do not know if manually running `post_setup.sh` works (I _think_ it's not), it's been a long time since I last looked at the BA NAS.

**Comment by rkozka** [comment]
I am wondering if new firmware on BA has changed somehow and its preventing this mod from running properly... I guess there is nothing more i can do.

**Comment by hn** [comment]
Closing issue, no more info received
