### ISSUE TITLE
Allowing drives from other manufacturers?

### ISSUE THREAD

**Issue by shsfunny** [hn/seagate-blackarmor-nas#4]
I apologize for logging this as an issue but I cant any other way to contact you. What in the device determines that a Seagate drive is installed? Is that check made in the Kernel? I want to fork off your code and remove this check thus allowing large drives from any manufacturer.

By the way, your firmware SP works on the BA 110 as well :) I tested it yesterday.

**Comment by hn** [comment]
It's perfectly fine to open an issue. This way other people can read and comment your thoughts.

I always thought that I had connected a non-Seagate drive during my initial tests and it worked. But I might remember wrong, I haven't used the BA NAS for years.

A quick grep through the firmware shows that there _might_ be such a check:

```
# rgrep WIX_STATE_HDD_NON_WD_HDD *
/etc/wixevent.h:    #define WIX_STATE_HDD_NON_WD_HDD 0x02   /* HDD - NOT made by Seagate */
/etc/eventtable.conf:WIX_EVENTTYPE_HDD              WIX_EVENT_ID_ALL                                WIX_STATE_HDD_NON_WD_HDD        WIX_EVENT_LEVEL_CRITICAL    "HDD Status"                                "HDD #ID is not made by Seagate"
/usr/share/wixevent/eventtable.conf.el:WIX_EVENTTYPE_HDD                WIX_EVENT_ID_ALL                            WIX_STATE_HDD_NON_WD_HDD        WIX_EVENT_LEVEL_CRITICAL    "Κατάσταση HDD"                                "Ο HDD #ID δεν έχει κατασκευαστεί από τη Seagate"
/usr/share/wixevent/eventtable.conf.de:WIX_EVENTTYPE_HDD                WIX_EVENT_ID_ALL                            WIX_STATE_HDD_NON_WD_HDD        WIX_EVENT_LEVEL_CRITICAL    "Festplattenstatus"                             "Festplatte #ID ist keine Seagate-Festplatte."
[...]
```

I do not know if this `define` is used at all (quite interestingly, it's called `NON_WD_HDD` and the descriptive text is for a non-Seagate HDD). Maybe it's a starting point for your work. Please share your findings with the community.

**Comment by shsfunny** [comment]
THANKS! I will look into it. Seagate mentions at the bottom of this article --
http://knowledge.seagate.com/articles/en_US/FAQ/212777en

That other off the shelf drives may work but I have been unable to find a single drive other than seagate drives that will function properly, I will look into this and see if I can make any changes. I will post the findings here.

**Comment by hn** [comment]
No info received, closing issue
